/install/etc/nginx/nginx.conf /etc/wlanpi-webui/nginx
/install/etc/nginx/wlanpi_librespeed.conf /etc/wlanpi-webui/nginx/sites-enabled
/install/etc/nginx/wlanpi_webui.conf /etc/wlanpi-webui/nginx/sites-enabled
/install/etc/nginx/link.sh /etc/wlanpi-webui/scripts
/install/etc/nginx/unlink.sh /etc/wlanpi-webui/scripts
/install/etc/nginx/fixpermissions.sh /etc/wlanpi-webui/scripts
/install/etc/cockpit/cockpit.conf /etc/cockpit
/install/etc/grafana/grafana.ini /etc/grafana